#!/usr/bin/env python3
"""
Script to encapsulate staged files from git into a Word document.
Similar to encapsulate_to_doc.py but specifically for git staged files.
"""

import os
import fnmatch
import base64
import json
import argparse
import sys
import subprocess
from pathlib import Path
from datetime import datetime
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH


class StagedFilesCreator:
    def __init__(self, output_file='staged_files.docx'):
        self.output_file = output_file
    
    def create_staged_document(self, file_patterns=None, exclude_patterns=None, use_git_staged=False, use_git_modified=False):
        """Create Word document with staged files"""
        if file_patterns is None:
            file_patterns = []
        if exclude_patterns is None:
            exclude_patterns = []
        
        # Get all files to stage
        files_to_stage = self.get_files_to_stage(file_patterns, exclude_patterns, use_git_staged, use_git_modified)
        
        if not files_to_stage:
            print("No files found matching the specified patterns.")
            return False
        
        # Create Word document
        doc = Document()
        
        # Add title
        title = doc.add_heading('Staged Files Documentation', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add metadata
        doc.add_heading('Metadata', level=1)
        metadata = {
            'total_files': len(files_to_stage),
            'file_patterns': file_patterns,
            'exclude_patterns': exclude_patterns,
            'staged_files': [str(f) for f in files_to_stage],
            'created_by': 'create_staged_files.py',
            'use_git_staged': use_git_staged,
            'use_git_modified': use_git_modified,
            'created_at': datetime.now().isoformat()
        }
        
        # Add metadata as text
        doc.add_paragraph(f"Total files included: {metadata['total_files']}")
        doc.add_paragraph(f"File patterns: {', '.join(file_patterns) if file_patterns else 'All files'}")
        doc.add_paragraph(f"Exclude patterns: {', '.join(exclude_patterns) if exclude_patterns else 'None'}")
        doc.add_paragraph(f"Generated by: {metadata['created_by']}")
        doc.add_paragraph(f"Created at: {metadata['created_at']}")
        doc.add_paragraph(f"From git staged: {use_git_staged}")
        doc.add_paragraph(f"From git modified: {use_git_modified}")
        
        # Add separator
        doc.add_page_break()
        
        # Add files
        doc.add_heading('Files', level=1)
        
        for i, file_path in enumerate(files_to_stage, 1):
            print(f"Processing {i}/{len(files_to_stage)}: {file_path}")
            
            # Add file header
            doc.add_heading(f"File: {file_path}", level=2)
            
            # Add file info
            try:
                file_size = file_path.stat().st_size
                doc.add_paragraph(f"Size: {file_size} bytes")
            except:
                doc.add_paragraph("Size: Unknown")
            
            # Add file content
            try:
                content = self.read_file_content(file_path)
                if content:
                    # Add content in a code block style
                    doc.add_paragraph("Content:")
                    content_para = doc.add_paragraph(content)
                    # Set font to monospace for code
                    for run in content_para.runs:
                        run.font.name = 'Courier New'
                else:
                    doc.add_paragraph("(Empty file)")
            except Exception as e:
                doc.add_paragraph(f"Error reading file: {str(e)}")
            
            # Add separator between files
            if i < len(files_to_stage):
                doc.add_paragraph("─" * 50)
        
        # Save document
        doc.save(self.output_file)
        print(f"\nDocument saved as: {self.output_file}")
        print(f"Total files included: {len(files_to_stage)}")
        
        return True
    
    def read_file_content(self, file_path):
        """Read file content, handling different encodings"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return f.read()
        except UnicodeDecodeError:
            try:
                with open(file_path, 'r', encoding='latin-1') as f:
                    return f.read()
            except UnicodeDecodeError:
                # For binary files, encode as base64
                with open(file_path, 'rb') as f:
                    content = f.read()
                    return f"[BINARY FILE - Base64 encoded]\n{base64.b64encode(content).decode('ascii')}"
    
    def get_git_staged_files(self):
        """Get list of files currently staged in git"""
        try:
            result = subprocess.run(['git', 'diff', '--cached', '--name-only'], 
                                  capture_output=True, text=True, check=True)
            staged_files = [line.strip() for line in result.stdout.split('\n') if line.strip()]
            return [Path(f) for f in staged_files if Path(f).exists()]
        except subprocess.CalledProcessError:
            return []
        except FileNotFoundError:
            print("Warning: git command not found. Falling back to pattern matching.")
            return []
    
    def get_git_modified_files(self):
        """Get list of modified files in git"""
        try:
            result = subprocess.run(['git', 'diff', '--name-only'], 
                                  capture_output=True, text=True, check=True)
            modified_files = [line.strip() for line in result.stdout.split('\n') if line.strip()]
            return [Path(f) for f in modified_files if Path(f).exists()]
        except subprocess.CalledProcessError:
            return []
        except FileNotFoundError:
            return []
    
    def get_files_to_stage(self, file_patterns, exclude_patterns, use_git_staged=False, use_git_modified=False):
        """Get list of files to stage based on patterns or git status"""
        import fnmatch
        
        all_files = []
        
        # Use git staged files if requested
        if use_git_staged:
            git_files = self.get_git_staged_files()
            if git_files:
                print(f"Found {len(git_files)} staged files in git")
                return git_files
            else:
                print("No staged files found in git")
                return []
        
        # Use git modified files if requested
        if use_git_modified:
            git_files = self.get_git_modified_files()
            if git_files:
                print(f"Found {len(git_files)} modified files in git")
                return git_files
            else:
                print("No modified files found in git")
                return []
        
        # Fall back to pattern matching
        root_path = Path('.').resolve()
        
        # If no patterns specified, stage all files (excluding common exclusions)
        if not file_patterns:
            file_patterns = ['*']
        
        # Default exclusions
        default_exclusions = [
            '.git/', '__pycache__/', '*.pyc', '*.pyo', 'venv/', '.venv/',
            'node_modules/', '.DS_Store', '*.log', '*.tmp', '*.swp'
        ]
        exclude_patterns.extend(default_exclusions)
        
        # Find all files
        for pattern in file_patterns:
            for file_path in root_path.rglob(pattern):
                if file_path.is_file():
                    # Check if file should be excluded
                    if not self.should_exclude_file(file_path, exclude_patterns):
                        all_files.append(file_path)
        
        # Remove duplicates and sort
        return sorted(list(set(all_files)))
    
    def should_exclude_file(self, file_path, exclude_patterns):
        """Check if file should be excluded"""
        import fnmatch
        
        normalized_path = str(file_path).replace('\\', '/')
        
        for pattern in exclude_patterns:
            if pattern.endswith('/'):
                if normalized_path.startswith(pattern) or f"/{pattern}" in normalized_path:
                    return True
            elif fnmatch.fnmatch(normalized_path, pattern) or fnmatch.fnmatch(file_path.name, pattern):
                return True
            elif pattern in normalized_path:
                return True
        
        return False
    
    def list_staged_files(self, use_git_staged=False, use_git_modified=False):
        """List all files that would be staged"""
        files_to_stage = self.get_files_to_stage([], [], use_git_staged, use_git_modified)
        
        if not files_to_stage:
            if use_git_staged:
                print("No staged files found in git.")
            elif use_git_modified:
                print("No modified files found in git.")
            else:
                print("No files found matching the specified patterns.")
            return
        
        if use_git_staged:
            print(f"Found {len(files_to_stage)} staged files in git:")
        elif use_git_modified:
            print(f"Found {len(files_to_stage)} modified files in git:")
        else:
            print(f"Found {len(files_to_stage)} files matching patterns:")
        
        for i, file_path in enumerate(files_to_stage, 1):
            print(f"  {i:3d}. {file_path}")


def main():
    parser = argparse.ArgumentParser(description='Encapsulate staged files into Word document')
    parser.add_argument('-o', '--output', default='staged_files.docx',
                       help='Output Word document filename (default: staged_files.docx)')
    parser.add_argument('-f', '--files', nargs='*', default=[],
                       help='File patterns to include (default: all files)')
    parser.add_argument('-e', '--exclude', nargs='*', default=[],
                       help='File patterns to exclude')
    parser.add_argument('--git-staged', action='store_true',
                       help='Use files currently staged in git')
    parser.add_argument('--git-modified', action='store_true',
                       help='Use files modified in git (not staged)')
    parser.add_argument('-l', '--list', action='store_true',
                       help='List files that would be staged')
    
    args = parser.parse_args()
    
    # Check if we're in a valid directory
    if not os.path.isdir('.'):
        print("Error: Not in a valid directory")
        sys.exit(1)
    
    creator = StagedFilesCreator(args.output)
    
    if args.list:
        creator.list_staged_files(args.git_staged, args.git_modified)
    else:
        success = creator.create_staged_document(args.files, args.exclude, args.git_staged, args.git_modified)
        if not success:
            sys.exit(1)


if __name__ == '__main__':
    main()
