#!/usr/bin/env python3
"""
Script to encapsulate all files in the current directory into a Word document.
Excludes files and folders specified in .ignoredoc (similar to .gitignore format).
Similar to the generate-doc npm package.
"""

import os
import fnmatch
import base64
import json
from pathlib import Path
from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import argparse
import sys


class FileEncapsulator:
    def __init__(self, ignore_file='.ignoredoc'):
        self.ignore_file = ignore_file
        self.ignore_patterns = []
        self.load_ignore_patterns()
    
    def load_ignore_patterns(self):
        """Load ignore patterns from .ignoredoc file"""
        if os.path.exists(self.ignore_file):
            with open(self.ignore_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    # Skip empty lines and comments
                    if line and not line.startswith('#'):
                        self.ignore_patterns.append(line)
        else:
            print(f"Warning: {self.ignore_file} not found. No files will be excluded.")
    
    def should_ignore(self, file_path):
        """Check if a file or directory should be ignored based on patterns"""
        # Convert to forward slashes for consistent pattern matching
        normalized_path = str(file_path).replace('\\', '/')
        
        for pattern in self.ignore_patterns:
            # Handle directory patterns (ending with /)
            if pattern.endswith('/'):
                if normalized_path.startswith(pattern) or f"/{pattern}" in normalized_path:
                    return True
            # Handle file patterns
            elif fnmatch.fnmatch(normalized_path, pattern) or fnmatch.fnmatch(os.path.basename(normalized_path), pattern):
                return True
            # Handle patterns that match any part of the path
            elif pattern in normalized_path:
                return True
        
        return False
    
    def get_all_files(self, root_dir='.'):
        """Get all files in the directory tree, excluding ignored ones"""
        files = []
        root_path = Path(root_dir).resolve()
        
        for file_path in root_path.rglob('*'):
            if file_path.is_file():
                # Get relative path from root
                rel_path = file_path.relative_to(root_path)
                if not self.should_ignore(rel_path):
                    files.append(rel_path)
        
        return sorted(files)
    
    def read_file_content(self, file_path):
        """Read file content, handling different encodings"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return f.read()
        except UnicodeDecodeError:
            try:
                with open(file_path, 'r', encoding='latin-1') as f:
                    return f.read()
            except UnicodeDecodeError:
                # For binary files, encode as base64
                with open(file_path, 'rb') as f:
                    content = f.read()
                    return f"[BINARY FILE - Base64 encoded]\n{base64.b64encode(content).decode('ascii')}"
    
    def create_document(self, output_file='codebase.docx'):
        """Create Word document with all files"""
        doc = Document()
        
        # Add title
        title = doc.add_heading('Codebase Documentation', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add metadata
        doc.add_heading('Metadata', level=1)
        metadata = {
            'total_files': 0,
            'excluded_patterns': self.ignore_patterns,
            'generated_by': 'encapsulate_to_doc.py'
        }
        
        # Get all files
        files = self.get_all_files()
        metadata['total_files'] = len(files)
        
        # Add metadata as JSON
        doc.add_paragraph(f"Total files included: {metadata['total_files']}")
        doc.add_paragraph(f"Excluded patterns: {', '.join(self.ignore_patterns)}")
        doc.add_paragraph(f"Generated by: {metadata['generated_by']}")
        
        # Add separator
        doc.add_page_break()
        
        # Add files
        doc.add_heading('Files', level=1)
        
        for i, file_path in enumerate(files, 1):
            print(f"Processing {i}/{len(files)}: {file_path}")
            
            # Add file header
            doc.add_heading(f"File: {file_path}", level=2)
            
            # Add file info
            full_path = Path(file_path)
            try:
                file_size = full_path.stat().st_size
                doc.add_paragraph(f"Size: {file_size} bytes")
            except:
                doc.add_paragraph("Size: Unknown")
            
            # Add file content
            try:
                content = self.read_file_content(full_path)
                if content:
                    # Add content in a code block style
                    doc.add_paragraph("Content:")
                    content_para = doc.add_paragraph(content)
                    # Set font to monospace for code
                    for run in content_para.runs:
                        run.font.name = 'Courier New'
                else:
                    doc.add_paragraph("(Empty file)")
            except Exception as e:
                doc.add_paragraph(f"Error reading file: {str(e)}")
            
            # Add separator between files
            if i < len(files):
                doc.add_paragraph("─" * 50)
        
        # Save document
        doc.save(output_file)
        print(f"\nDocument saved as: {output_file}")
        print(f"Total files included: {len(files)}")
        print(f"Files excluded by patterns: {len(self.ignore_patterns)} patterns")


def main():
    parser = argparse.ArgumentParser(description='Encapsulate codebase files into a Word document')
    parser.add_argument('-o', '--output', default='codebase.docx', 
                       help='Output Word document filename (default: codebase.docx)')
    parser.add_argument('-i', '--ignore', default='.ignoredoc',
                       help='Ignore file with patterns (default: .ignoredoc)')
    
    args = parser.parse_args()
    
    # Check if we're in a valid directory
    if not os.path.isdir('.'):
        print("Error: Not in a valid directory")
        sys.exit(1)
    
    # Create encapsulator and generate document
    encapsulator = FileEncapsulator(args.ignore)
    encapsulator.create_document(args.output)


if __name__ == '__main__':
    main()
