#!/usr/bin/env python3
"""
Script to restore files and folder structure from a Word document.
Similar to the restore-from-doc npm package.
"""

import os
import re
import base64
import argparse
import sys
from pathlib import Path
from docx import Document
import json


class FileRestorer:
    def __init__(self):
        self.files_data = []
        self.metadata = {}
    
    def parse_document(self, doc_file):
        """Parse the Word document and extract file information"""
        print(f"Parsing document: {doc_file}")
        
        try:
            doc = Document(doc_file)
        except Exception as e:
            print(f"Error opening document: {e}")
            return False
        
        current_file = None
        in_content = False
        content_lines = []
        
        for paragraph in doc.paragraphs:
            text = paragraph.text.strip()
            
            # Check for metadata section
            if text.startswith('Total files included:'):
                self.metadata['total_files'] = int(text.split(':')[1].strip())
            elif text.startswith('Excluded patterns:'):
                patterns_text = text.split(':', 1)[1].strip()
                self.metadata['excluded_patterns'] = [p.strip() for p in patterns_text.split(',')]
            elif text.startswith('Generated by:'):
                self.metadata['generated_by'] = text.split(':', 1)[1].strip()
            
            # Check for file headers
            elif text.startswith('File: '):
                # Save previous file if exists
                if current_file:
                    self.save_file_data(current_file, content_lines)
                
                # Start new file
                file_path = text[6:]  # Remove "File: " prefix
                current_file = {
                    'path': file_path,
                    'size': None,
                    'content': []
                }
                content_lines = []
                in_content = False
            
            # Check for file size
            elif text.startswith('Size: ') and current_file:
                size_text = text[6:]  # Remove "Size: " prefix
                if size_text != 'Unknown':
                    try:
                        current_file['size'] = int(size_text.split()[0])
                    except:
                        pass
            
            # Check for content marker
            elif text == 'Content:' and current_file:
                in_content = True
                continue
            
            # Check for separator (end of file content)
            elif text.startswith('─' * 50) and current_file:
                if in_content:
                    self.save_file_data(current_file, content_lines)
                    current_file = None
                    content_lines = []
                    in_content = False
                continue
            
            # Collect content lines
            elif in_content and current_file:
                content_lines.append(paragraph.text)
        
        # Save last file if exists
        if current_file:
            self.save_file_data(current_file, content_lines)
        
        print(f"Parsed {len(self.files_data)} files from document")
        return True
    
    def save_file_data(self, file_info, content_lines):
        """Save file data to the files_data list"""
        content = '\n'.join(content_lines)
        
        # Check if it's a binary file
        if content.startswith('[BINARY FILE - Base64 encoded]'):
            # Extract base64 content
            base64_content = content.split('\n', 1)[1]
            try:
                binary_data = base64.b64decode(base64_content)
                file_info['content'] = binary_data
                file_info['is_binary'] = True
            except Exception as e:
                print(f"Warning: Could not decode binary content for {file_info['path']}: {e}")
                file_info['content'] = content
                file_info['is_binary'] = False
        else:
            file_info['content'] = content
            file_info['is_binary'] = False
        
        self.files_data.append(file_info)
    
    def restore_files(self, output_dir='.'):
        """Restore all files to the filesystem"""
        output_path = Path(output_dir).resolve()
        
        print(f"Restoring files to: {output_path}")
        
        # Create output directory if it doesn't exist
        output_path.mkdir(parents=True, exist_ok=True)
        
        restored_count = 0
        error_count = 0
        
        for file_info in self.files_data:
            try:
                file_path = output_path / file_info['path']
                
                # Create parent directories
                file_path.parent.mkdir(parents=True, exist_ok=True)
                
                # Write file content
                if file_info.get('is_binary', False):
                    with open(file_path, 'wb') as f:
                        f.write(file_info['content'])
                else:
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(file_info['content'])
                
                print(f"Restored: {file_info['path']}")
                restored_count += 1
                
            except Exception as e:
                print(f"Error restoring {file_info['path']}: {e}")
                error_count += 1
        
        print(f"\nRestoration complete:")
        print(f"  Files restored: {restored_count}")
        print(f"  Errors: {error_count}")
        
        if self.metadata:
            print(f"\nOriginal metadata:")
            print(f"  Total files: {self.metadata.get('total_files', 'Unknown')}")
            print(f"  Generated by: {self.metadata.get('generated_by', 'Unknown')}")
    
    def list_files(self):
        """List all files that would be restored"""
        print("Files in document:")
        for i, file_info in enumerate(self.files_data, 1):
            size_info = f" ({file_info['size']} bytes)" if file_info['size'] else ""
            binary_info = " [BINARY]" if file_info.get('is_binary', False) else ""
            print(f"  {i:3d}. {file_info['path']}{size_info}{binary_info}")


def main():
    parser = argparse.ArgumentParser(description='Restore files from a Word document')
    parser.add_argument('doc_file', help='Word document file to restore from')
    parser.add_argument('-o', '--output', default='.', 
                       help='Output directory (default: current directory)')
    parser.add_argument('-l', '--list', action='store_true',
                       help='List files in document without restoring')
    
    args = parser.parse_args()
    
    # Check if document file exists
    if not os.path.exists(args.doc_file):
        print(f"Error: Document file '{args.doc_file}' not found")
        sys.exit(1)
    
    # Create restorer and parse document
    restorer = FileRestorer()
    
    if not restorer.parse_document(args.doc_file):
        print("Error: Failed to parse document")
        sys.exit(1)
    
    if args.list:
        restorer.list_files()
    else:
        # Confirm restoration
        print(f"About to restore {len(restorer.files_data)} files to '{args.output}'")
        response = input("Continue? (y/N): ").strip().lower()
        
        if response in ['y', 'yes']:
            restorer.restore_files(args.output)
        else:
            print("Restoration cancelled")


if __name__ == '__main__':
    main()
